cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/services'
tap 'robotsandpencils/made'

brew 'cocoapods'
brew 'fastlane'
brew 'firefox'
brew 'git'
brew 'rbenv'
brew 'ruby-build'
brew 'xcodes'
brew 'zsh'

cask '1password'
cask 'asana'
cask 'autodesk-fusion360'
cask 'db-browser-for-sqlite'
cask 'charles'
cask 'isimulator'
cask 'iterm2'
cask 'lulu'
cask 'notion'
cask 'obs'
cask 'paw'
cask 'signal'
cask 'slack'
cask 'sourcetree'
cask 'spectacle'
cask 'telegram'
cask 'toggl-track'
cask 'visual-studio-code'
cask 'zoom'
